amsynth/amsynth

- COPYING
Hi,
I currently package amsynth for Fedora, and the package-review tool complains about the FSF address (you use the old one): "E: incorrect-fsf-address /usr/share/licenses/amsynth/COPYING ".
Here is the corrected address, based on http://www.gnu.org/licenses/gpl-2.0.txt
Thank you in advance
> Update FSF address

- src/Synthesizer.cpp
Hi
Just added few lines to allow the use of microtonal tunings in plugins (at least with dssi) through the conf file. It builds and works fine with rosegarden in Fedora 24.
I don't know if it is the better way to make it work, but it works :)
> Allow microtonal in plugins

- data/amsynth.1
- data/amsynth.fr.1
Please find man pages built from the return of `amsynth -h`. Hope you'll find them useful.
Please, have a look to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836878 as well. It's over my competences, but you might understand better than me what Jonas says there.
Hopes that helps
> Adds EN and FR manpages

- Makefile.am
- configure.ac
- data/amsynth.appdata.xml.in
- po/POTFILES.in
- po/POTFILES.skip
Appdata files are used to generate appstream metadata which is
then used by software stores like gnome-software and plasma-discover
to display the app in its list of available apps for installation.
Basically, installing this appdata file makes your app show up
in these kind of appstream dependent appstores, thus making the
app easily discoverable, installable and reviewable.
The appdata file added here is set up to be translatable using
usual GETTEXT methods, once the appropriate strings are added to
the po files.
See the appdata specification:
https://www.freedesktop.org/software/appstream/docs/
> Add and install an appdata file (translatable).

- src/GUI/GUI.cc
This PR cleans up ellipses in menu items and dialog titles.
I removed ellipses from dialog titles and adjusted some menu item labels; they now contain ellipses (more or less) if more user input is requested after selecting the menu item.
You can find relevant quotes from several user interface guidelines in [this Stack Overflow answer](https://stackoverflow.com/a/637708) for example.
> Ellipsis cleanup

- src/main.cc
Help output (`amsynth -h`) was misaligned due to a long place holder string and a stray tab.
> Align help output

- data/amsynth.1
- data/rc
- src/GUI/GUI.cc
- src/drivers/ALSAMidiDriver.cc
- src/main.cc
I left the following strings as-is for now - should they also be changed? The first NEWS entry looks like an issue/pull request title though.
```
AUTHORS: - Input on the GUI - new midi controller config, motivating re-organisation of menus, shortcut keys..
AUTHORS: - Added midi out capabilities for control surfaces with feedback
NEWS:  - #26 setting midi channel from command line
NEWS:  * handle all notes off midi message
src/tests.cpp:        assert(midiOut.empty() || !"no midi output should be generated when a cc is processed");
src/tests.cpp:    assert(midiOut.size() == 1 || !"midi output should be generated when a parameter is changed");
src/tests.cpp:    assert(midiOut[0].value == 0 || !"midi output value is incorrect");
```
> Fix MIDI capitalization in user-visible strings

- src/GUI/GUI.cc
This adds [VMPK](http://vmpk.sourceforge.net) (a virtual keyboard) and [Patchage](https://drobilla.net/software/patchage) (an ALSA/JACK patch bay) to the utils menu and moves virtual keyboards into their own sub-menu.
The VMPK menu entry simply starts vmpk; the ALSA/JACK Patchage entries start patchage with the respective command line option to disable JACK/ALSA auto-connecting.
I based the code on the existing menu entries (didn't use GTK+/gtkmm before), so please take a closer look if you want to merge this. Also, Patchage is only available for Linux and Mac OS X; should the respective menu entries be hidden on Windows?
If you don't want to merge this (e.g. to avoid collecting applications in the utils menu), that's fine with me.
> Add VMPK and Patchage to utils menu

- src/Preset.h
Otherwise we get temporary objects with non deterministic lifetime. Errors
caused are e.g mangled names in dssi get_program. Not easy to debug believe
me!
Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
> Preset: return reference to mName

- src/Preset.h
- src/dssi.cpp
These two patches make all presets selectable from sequencer application. It was tested with qtractor. I know it does not play well with the DSSI GUI but it is a start and I am working on it.
> Make DSSI Plugin presets selectable from host application

- src/GUI/GUI.cc
The American English spelling is also used in the following places:
README file, AppData file, .desktop file, website, repository description.
> Fix inconsistent spelling of "analog"

- po/Makevars
- src/GUI/GUI.cc
The prefix for these comments is set to `@translators`.
Example comment: `// @translators: This is a comment for translators`
As a side effect, this change also causes the removal of some leftover comments from the translation files the next time they are regenerated.
> Enable extraction of comments for translators and add two such comments

- .gitignore
- Makefile.am
- configure.ac
- po/POTFILES.skip
Previously, the untranslated, marked-up-for-translation AppData file simply was copied to its final location instead of being processed further.
This change removes the file from `AC_OUTPUT` - preventing the simple copying - and adds it to `DISTCLEANFILES` for cleanup. Also, `POTFILES.skip` is no longer needed according to `intltool-update --maintain`.
Documentation: [CONFIG_FILES](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Configuration-Files.html#index-AC_005fCONFIG_005fFILES-79) via [AC_OUTPUT (Obsolete Macros)](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Obsolete-Macros.html#index-AC_005fOUTPUT-2133) via [AC_OUTPUT](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Output.htm …
> Fix generation of translated AppData file

- data/amsynth.lv2/amsynth.ttl
- src/Preset.cc
Now, the first/left waveform listed (triangle) corresponds to the shape knob turned left (triangle wave) and the second/right one (saw) to the shape knob turned right (sawtooth wave).
I checked the waveforms corresponding to left/right knob positions using glfer.
Are the .ttl adjustments OK?
> Exchange entries of saw/triangle OSC waveform label

- data/amsynth.1.md
- data/amsynth.fr.1.md
The `NAME` section changes are based on the .desktop file's `Comment` entries, the `ENVIRONMENT` additions on 490c0e8 and the skinning `README`.
@trebmuh: Are these changes OK? Please check my French translations in particular as well as the adjusted author information. The latter is not optimal, but I hope it's acceptable this way (suggestions welcome). Also, the French man page still contains some untranslated strings.
> Improve man pages

- Makefile.am
This is now possible since only release information in the man page footer needs to be set.
Documentation: [pandoc templates](https://pandoc.org/MANUAL.html#templates), [variables for man pages](https://pandoc.org/MANUAL.html#variables-for-man-pages) (for `footer`)
> Insert release information into man pages using pandoc

- Makefile.am
- configure.ac
This adds a `./configure` option: `--with-pandoc`
* `--with-pandoc` enables man page generation and errors out if pandoc has not been found
* `--without-pandoc` disables man page generation
* if neither of these is given, man page generation is enabled/disabled automatically depending on the availability of pandoc
Changed build dependency: pandoc is now optional
This closes #79.
@nixxcode: This works for me (on Linux), but please thoroughly check the changes.
> Make man page generation optional

- src/GUI/editor_menus.cpp
This fix an error during build with gcc-7.1.1:
format not a string literal and no format arguments
The problem was a non-const *char passed to gtk2 function that only accept const *char
> Fix String format security with gtk2

- Makefile.am
The pattern matching for appdata_DATA was too specific and missed
including the appdata for plugins, which are named .metainfo.xml
instead of .appdata.xml. Relax the pattern so that all .xml.in
files are included, and translated to corresponding .xml files.
> Ensure plugin metainfo is translated and installed.

- data/lv2-amsynth-plugin.metainfo.xml.in
- data/vst-amsynth-plugin.metainfo.xml.in
- src/GUI/MainMenu.cpp
- src/GUI/editor_menus.cpp
@nixxcode: There are two different versions of the tuning scale/keymap error messages which are also modified in the first commit - with line breaks in `src/GUI/editor_menus.cpp`, without line breaks in `src/GUI/MainMenu.cpp`. Is this on purpose or can these strings be unified?
> Fix inconsistencies and typos in user-visible strings

- Makefile.am
Without this there are several *.metainfo.xml.in files.
Stolen from fedora [1]
[1] https://src.fedoraproject.org/rpms/amsynth/blob/master/f/amsynth.fixMetainfo.patch
Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
> Fix installing of appdata

- src/GUI/PresetControllerView.cpp
Compiling with -Wformat-overflow, GCC report this warning
> Fix a format overflow compiler warning

- src/AudioOutput.h
Returning anything but 0 (or false) is the same as returning true in a 
function with bool as return value type. Return false instead.
> Do not return -1 in as bool

- src/Preset.cpp
The static variable _preset can be uninitialized when the library constructor
runs. When it happens, the parameters and their names are not enumerated
correctly in the DSSI descriptor.
#137
> Fix issue of static initialization order

- src/GUI/PresetControllerView.cpp
- src/GUI/editor_menus.cpp
- src/amsynth_dssi.cpp
Eliminating the copy accelerates the program listing by a vast amount.
In DSSI, performance is a problem with naspro-bridges installed, because when it lists program in a loop as the host loads LV2, the host will hang for a whole minute while it processes.
Before: `./load-amsynth .libs/amsynth_dssi.so  58,52s user 0,19s system 98% cpu 59,699 total`
After: `./load-amsynth .libs/amsynth_dssi.so  0,37s user 0,05s system 98% cpu 0,421 total`
I've applied some identical changes throughout the program.
[load-amsynth.cc.gz](https://github.com/amsynth/amsynth/files/3236815/load-amsynth.cc.gz)
> Improve preset listing performance

- src/GUI/editor_pane.c
Fixes a segfault when loading a custom skin from a directory pointed to by the AMSYNTH_SKIN environment variable.
> Fix a segfault when trying to free an environment variable.

- NEWS
- src/GUI/bitmap_button.c
- src/GUI/bitmap_button.h
- src/GUI/bitmap_knob.c
- src/GUI/bitmap_knob.h
- src/GUI/bitmap_popup.c
- src/GUI/bitmap_popup.h
- src/GUI/editor_pane.c
- src/VoiceBoard/VoiceBoard.cpp
This patch improves the appearance of the graphical "editor" area (knobs and buttons etc.) when using a HiDPI display with a scale factor. The results are quite blurry due to upscaling the low-resolution graphics, but better than having a tiny UI.
It reads the `org.gnome.desktop.interface` `scaling-factor` setting to determine by how much to scale the controls and background.
Note that other icons in the app (in File dialogs, toolbars, checkboxes, About dialog) do not respect the scaling factor, as GTK2 does not natively support this.
Tested and verified on Pop!OS 20.04 LTS using GNOME & X11 windowing system. Not able to try Wayland as my computer has NVIDIA graphics.
> HiDPI scaling

- configure.ac
'==' is an extension supported by only some implementations like bash and ksh, it's otherwise identical to '='.
> POSIX shell portability: Use '=' instead of '=='

- src/GUI/MainMenu.cpp
- src/MidiController.cpp
- src/MidiController.h
- src/Synthesizer.cpp
- src/drivers/ALSAMidiDriver.cpp
- src/drivers/MidiDriver.h
- src/drivers/OSSMidiDriver.cpp
- src/main.cpp
Stops settings from configuration file (represented by `Configuration`) being applied to plug-in instances.
Resolves #173
> Ignore app settings in plugins

- data/amsynth.lv2/PatriksBank02.bank.ttl
- data/amsynth.lv2/amsynth.ttl
data/amsynth.lv2/PatriksBank02.bank.ttl,data/amsynth.lv2/amsynth.ttl:
The URI for "PatriksBank02: 046" is not valid, as it contains literal
double quotes (").
The rdfs:label due to internal doube quotes is also invalid.
By removing the double quotes from the URI and single-quoting the
rdfs:label entries lv2lint is able to validate the files again.
Fixes #178
> Fix PatriksBank02: 046

- data/amsynth.lv2/PatriksBank02.bank.ttl
- data/amsynth.lv2/amsynth.ttl
- utils/lv2_presets.py
A more permanent fix for lv2lint validation failure #178
> Fix LV2 preset generation for names containing ‘“‘

- po/POTFILES.in
- po/de.po
- po/fr.po
- src/Parameter.cpp
- src/Parameter.h
- src/Preset.cpp
- src/Preset.h
- src/PresetController.cpp
- src/controls.h
Defines parameter limits & curves as a read-only struct array instead of being included in each `Parameter` object, reducing code size and runtime overhead.
Moves implementation of parameter related functions from `Preset.cpp` to `Parameter.cpp`.
> Refactor parameter declarations

- src/main.cpp
I tried to add the CLI option to specify which preset to use (which I asked about in issue #219 ), but realized it's already implemented, it's just not specified in the help menu.
> Add information about -P option in the help menu

- src/core/midi.h
- src/core/synth/MidiController.cpp
Added the following MIDI CC as default mapping:
```
MIDI CC 5  :  kAmsynthParameter_PortamentoTime
MIDI CC 71 :  kAmsynthParameter_FilterResonance
MIDI CC 72 :  kAmsynthParameter_AmpEnvRelease
MIDI CC 73 :  kAmsynthParameter_AmpEnvAttack
MIDI CC 74 :  kAmsynthParameter_FilterCutoff
MIDI CC 91 :  kAmsynthParameter_ReverbWet
```
> Add common default MIDI controllers
